### ISSUE TITLE
Unable to enable add-on

### ISSUE THREAD

**Issue by MichalStaruch** [prman-pixar/RenderManForBlender#529]
**Environment:**
Blender version: 2.78c
RenderMan version: 21.5 NCR (only one available for download)
RenderMan for Blender version: 21.4 (latest available)
OS: Windows 10 build 1703, 64-bit
Both Blender and RenderMan installed on D:\ drive.
Logged in as non-privileged user.

**Reproduction steps:**
1. Install Blender in non-default path.
2. Install RenderMan in non-default path.
3. Install plugin (Blender, File -> User Preferences... -> Add-ons -> Install from File...).
4. Try to click on empty box near "RenderMan For Blender" (with "Enable an add-on" hint).

**Current result:**
Stack trace from addon_utils.py, line 349 in enable mod.register(), as on attached screenshot:

![image](https://user-images.githubusercontent.com/295215/28751965-9d7fa016-7514-11e7-806d-64dc0862da02.png)

**Expected result (in order of preference):**
1. Add-on successfully enabled.
2. Hint what should be done to make it work.
3. Explanation why it can't work (for example incompatible versions of RenderMan and the add-on).

**Comment by MichalStaruch** [comment]
Current version from master (commit 22787e2fc0c55746d3baf3013233cd4e8619cc0d) allows plugin to be enabled, but attempt to render initial cube scene result in "PRMan: Exited" error.

PS When setting RMANTREE I've notice it was just the RenderMan Installer which made up into D:\ - RenderManProServer itself ended up in C:\Program Files\. Blender was restarted after setting env value.

**Comment by shinmai** [comment]
Same symptoms except I'm gettign a different error:

```
renderman_for_blender updater verbose is enabled
renderman_for_blender Updater: Read in json settings from file
Exception in module register(): 'C:\\Users\\default\\AppData\\Roaming\\Blender Foundation\\Blender\\2.78\\scripts\\addons\\RenderManForBlender-21_4_0\\__init__.py'
Traceback (most recent call last):
  File "C:\blender\2.78\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\__init__.py", line 121, in register
    load_addon()
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\__init__.py", line 109, in load_addon
    nodes.register()
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\nodes.py", line 2266, in register
    vals = generate_node_type(prefs, name, ET.parse(arg_file).getroot())
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\nodes.py", line 669, in generate_node_type
    class_generate_properties(ntype, name, inputs + outputs)
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\shader_parameters.py", line 175, in class_generate_properties
    sp, node, page_name, first_level=first_level)
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\shader_parameters.py", line 85, in generate_page
    name, meta, prop = generate_property(sub_param)
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\shader_parameters.py", line 448, in generate_property
    sp.find("hintdict[@name='conditionalVisOps']"))
  File "C:\Users\default\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender-21_4_0\shader_parameters.py", line 366, in parse_conditional_visop
    "string[@name='conditionalVisPath']").attrib['value']
AttributeError: 'NoneType' object has no attribute 'attrib'
```

**Comment by bsavery** [comment]
The latest master branch has the above error fixed.

**Comment by MichalStaruch** [comment]
I found root cause when I tried to manually launch prman.exe - I was getting the ```R50009 {SEVERE}  License location is not set in renderman.ini - aborting.``` error. I uninstalled RenderMan and installed again in the default location - error is gone.

I've got back to Blender - add-on from master started to work. Current release version of the add-on (21.4) doesn't work, though.

Two actions could help to avoid that kind of problems:
1. Release add-on version compatible with current RenderMan (21.5).
2. Consider forwarding more detailed error messages from prman.exe to the UI or console in Blender (to speed-up troubleshooting).

**Comment by shinmai** [comment]
> The latest master branch has the above error fixed.  

This is accurate, cloning the repo to Blender's addon directory allowed me to enable the add-on without errors. Thanks. 
I'll file a separate issue for the segfault that seems to always happen at one point or another during rendering.

**Comment by Didsonthego** [comment]
Is there a fix yet? getting errors too!

**Comment by utak3r** [comment]
I took the last release and patched with only the activation fix - and it's working as expected. Activates and renders as it should.

**Comment by alkaris2** [comment]
This is the error I get when I try to enable RenderMan for Blender.

![image](https://user-images.githubusercontent.com/73155407/162560792-feff42b8-7518-4ca3-ad68-aa0277fd42a4.png)

**Comment by pleprince** [comment]
@alkaris2 Python 3.10 is not supported yet. You should use Blender 3.0 instead of 3.1.
