### ISSUE TITLE
Ribgen error

### ISSUE THREAD

**Issue by AndreasReschGFX** [prman-pixar/RenderManForBlender#540]
Hello,

I have a scene that checks out fine in IPR but then I want to render it in final quality, I get random RIB gen errors. Sometimes it affects a specific object and on the next run it affects some other objects. It seems as it only affects objects that have a Subdivision Surface Modifier applied to the. Sometimes it works fine with no errors at all. 

Here's the error message that I get ...

Rib gen error exporting C:\Temp\Renderman\Renderman_Test_119\archives\static\Cube.019.Cylinder.011-MESH.rib: Traceback (most recent call last):
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 2126, in export_data_archives
    export_mesh_archive(ri, scene, db)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 2480, in export_mesh_archive
    export_geometry_data(ri, scene, ob)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 1728, in export_geometry_data
    export_subdivision_mesh(ri, scene, ob, data)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 1321, in export_subdivision_mesh
    mesh = data if data is not None else create_mesh(ob, scene)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 644, in create_mesh
    ob.modifiers[len(ob.modifiers) - 1].show_render = False
AttributeError: Writing to ID classes in this context is not allowed: Cube.019, Object datablock, error setting SubsurfModifier.show_render

Rib gen error exporting C:\Temp\Renderman\Renderman_Test_119\archives\static\Cube.006.Roundcube-MESH.rib: Traceback (most recent call last):
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 2126, in export_data_archives
    export_mesh_archive(ri, scene, db)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 2480, in export_mesh_archive
    export_geometry_data(ri, scene, ob)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 1728, in export_geometry_data
    export_subdivision_mesh(ri, scene, ob, data)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 1321, in export_subdivision_mesh
    mesh = data if data is not None else create_mesh(ob, scene)
  File "C:\Users\Sammy\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RenderManForBlender_master\export.py", line 644, in create_mesh
    ob.modifiers[len(ob.modifiers) - 1].show_render = False
AttributeError: Writing to ID classes in this context is not allowed: Cube.006, Object datablock, error setting SubsurfModifier.show_render

Cheers,
Andreas

**Comment by bsavery** [comment]
That line can be taken out of the code.  Because the plugin turns off tesselation when calling create_mesh() it's the same as turning off the subsurf modifier.

**Comment by AndreasReschGFX** [comment]
Hey Brian,

but turning off the SS modifier will result in coarser geometry.

**Comment by bsavery** [comment]
Sorry if I wasn't exactly clear.  
RenderMan does subdivisions at rendertime (similar to cycles adaptive subdivs only done 25 years ago).  For that reason we don't need the fully subdivided mesh when doing ribgen.  That's the idea of that line above, but we can (and do) achieve the same thing with the create_mesh(.... tesselate=False) method.

**Comment by AndreasReschGFX** [comment]
I see,

so you take the coarse mesh and add the subdivison level as a variable. That's fine. The odd thing is, that this error comes randomly. It affects different objects every time. Sometimes no error happens.

If removing that line results in the same outcome and the errors are gone - I'd ditch it. May be confusing to users if they see errors popping up all the time.

Cheers,
Andreas

**Comment by bsavery** [comment]
Yeah the random part I have no idea.  very strange.  But removing the line in error should be safe.
