### ISSUE TITLE
Error when Installing Addon

### ISSUE THREAD

**Issue by JulianHa** [prman-pixar/RenderManForBlender#571]
Every time I try to enable the addon, python spits out the following error message 

`Imported multifiles
TypeError: BoolProperty(): 'Texture.Filtering And Defaults.Advanced Texture Settings_ui_open' too long, max length is 63
Exception in module register(): 'C:\\Users\\Deadsec01\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\RenderManForBlender-21_5_0\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\Deadsec01\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-21_5_0\__init__.py", line 119, in register
    load_addon()
  File "C:\Users\Deadsec01\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-21_5_0\__init__.py", line 108, in load_addon
    nodes.register()
  File "C:\Users\Deadsec01\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-21_5_0\nodes.py", line 2266, in register
    vals = generate_node_type(prefs, name, ET.parse(arg_file).getroot())
  File "C:\Users\Deadsec01\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-21_5_0\nodes.py", line 681, in generate_node_type
    bpy.utils.register_class(ntype)
ValueError: bpy_struct "PxrLayeredTexturePatternNode" registration error: Texture.Filtering And Defaults.Advanced Texture Settings_ui_open could not register`

**Comment by adminradio** [comment]
For RenderMan 21.7 you need to install from current master:
https://github.com/prman-pixar/RenderManForBlender/archive/master.zip
