### ISSUE TITLE
Prman for Python is not defined

### ISSUE THREAD

**Issue by dpastorv** [prman-pixar/RenderManForBlender#576]
I've got this weird error. No issues at install, but no preview as shown.

![image](https://user-images.githubusercontent.com/18488620/40384330-d097c364-5dc8-11e8-86d3-1beb884f80da.png)

Also if I try to render on the preview it displays like this.
![image](https://user-images.githubusercontent.com/18488620/40384453-34baa488-5dc9-11e8-9621-8bce200df90b.png)

and when I try to render in IPR i got this 
![image](https://user-images.githubusercontent.com/18488620/40384510-642ca914-5dc9-11e8-9d26-896c0d36194a.png)

in the console the error displays like this.
Exception ignored in: <bound method RPass.__del__ of <RenderManForBlender-master.engine.RPass object at 0x0000020AEA51F630>>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\engine.py", line 220, in __del__
    del self.ri
AttributeError: ri
Exception ignored in: <bound method PRManRender.__del__ of <bpy_struct, PRManRender invalid>>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\__init__.py", line 51, in __del__
    if hasattr(self, "render_pass"):
ReferenceError: StructRNA of type PRManRender has been removed
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\__init__.py", line 61, in update
    engine.create(self, data, scene)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\engine.py", line 104, in create
    engine.render_pass = RPass(scene, preview_render=engine.is_preview)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\engine.py", line 204, in __init__
    init_prman()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\engine.py", line 79, in init_prman
    import prman
  File "C:\Program Files\Pixar\RenderManProServer-21.7\bin\prman.py", line 102, in <module>
    class Rif(prman_for_python.Rif):
NameError: name 'prman_for_python' is not defined

location: <unknown location>:-1

**Comment by davideo** [comment]
I would like to know the answer to this question as well as I am getting the same behavior since I installed Renderman 21.7 on Blender 2.79b on Linux Mint 18. Usually, I can shoot down these errors myself but this one has proved intractable for me. Thanks for any guidance!

**Comment by jdent02** [comment]
Something is going wrong with the import of the Renderman Python module from the look of it.

**Comment by minerscale** [comment]
I'm having the same issue on Ubuntu 17.10

**Comment by jdent02** [comment]
Blender uses python 3.5 so it can’t be run in 2.7 from within blender.  Blenders been on python 3 for a while so it’s unusual that prman would work for this long and then all of a sudden develop issues

**Comment by minerscale** [comment]
PRMan for Python itself says it only supports 2.5: https://renderman.pixar.com/resources/RenderMan_20/prmanForPython.html#caveats-limitations-future-directions

**Comment by jdent02** [comment]
At the time that article was written (April 2009) that was true, but Python 3 bindings were added later on.  You can’t run a Python 2.7 module in Blender.  It requires Python 3, which is one of the reasons why the VFX industry still avoids Blender to some extent.  Most of them are still using Python 2.7 for their pipelines.

**Comment by adminradio** [comment]
Reinstall the addon without any spaces or hyphens in the addon directory name (remove "-master" from directory name. Then it should run.

**Comment by schroef** [comment]
> Reinstall the addon without any spaces or hyphens in the addon directory name (remove "-master" from directory name. Then it should run.

I tried that and still see the error, i see these error when doing render using blender

```
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/__init__.py", line 64, in update
    engine.create(self, data, scene)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 104, in create
    engine.render_pass = RPass(scene, preview_render=engine.is_preview)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 204, in __init__
    init_prman()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 79, in init_prman
    import prman
  File "/Applications/Pixar/RenderManProServer-22.2/bin/prman.py", line 80, in <module>
    import prman_for_python_35 as prman_for_python
ImportError: dlopen(/Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python
  Referenced from: /Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so
  Reason: image not found
```

This is the output for IPR render using blender
```
Exception ignored in: <bound method RPass.__del__ of <RenderManForBlender.engine.RPass object at 0x11bcd86a0>>
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 220, in __del__
    del self.ri
AttributeError: ri
Exception ignored in: <bound method PRManRender.__del__ of <bpy_struct, PRManRender invalid>>
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/__init__.py", line 51, in __del__
    if hasattr(self, "render_pass"):
ReferenceError: StructRNA of type PRManRender has been removed
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/operators.py", line 492, in invoke
    engine.ipr = RPass(context.scene, interactive=True)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 204, in __init__
    init_prman()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 79, in init_prman
    import prman
  File "/Applications/Pixar/RenderManProServer-22.2/bin/prman.py", line 80, in <module>
    import prman_for_python_35 as prman_for_python
ImportError: dlopen(/Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python
  Referenced from: /Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so
  Reason: image not found
```

This is when i tried using TR for render to
```
Exception ignored in: <bound method RPass.__del__ of <RenderManForBlender.engine.RPass object at 0x11bce5e80>>
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 217, in __del__
    if self.is_interactive and self.is_prman_running():
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 561, in is_prman_running
    return prman.RicGetProgress() < 100
NameError: name 'prman' is not defined
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/operators.py", line 492, in invoke
    engine.ipr = RPass(context.scene, interactive=True)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 204, in __init__
    init_prman()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 79, in init_prman
    import prman
  File "/Applications/Pixar/RenderManProServer-22.2/bin/prman.py", line 80, in <module>
    import prman_for_python_35 as prman_for_python
ImportError: dlopen(/Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python
  Referenced from: /Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so
  Reason: image not found
```

Im tried both bl 2.78c and 2.79b on osx 10.11.6

**Comment by schroef** [comment]
> Blender uses python 3.5 so it can’t be run in 2.7 from within blender. Blenders been on python 3 for a while so it’s unusual that prman would work for this long and then all of a sudden develop issues

Im just new to this renderman, but i did see this on a page. https://github.com/prman-pixar/RenderManForBlender/issues/580

<img width="917" alt="screen shot 2018-11-18 at 19 03 56" src="https://user-images.githubusercontent.com/6923008/48679277-bb834780-eb64-11e8-91c6-2602b6e5e53c.png">

Though on that other page something else is stated indeed
https://renderman.pixar.com/resources/RenderMan_20/prmanForPython.html#caveats-limitations-future-directions
<img width="844" alt="screen shot 2018-11-18 at 19 04 24" src="https://user-images.githubusercontent.com/6923008/48679283-ca69fa00-eb64-11e8-9df6-e9fbcf46cfb8.png">

**Comment by jdent02** [comment]
It works with 3.5 as it launches with blender 2.79b

**Comment by schroef** [comment]
I did notice just now that it also doesnt seem to find the python lib in the frameworks folder. There is no 3.5 in that folder only 3.4 and 3.6?

That is at the bottom of the error
```
ImportError: dlopen(/Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python
  Referenced from: /Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so
  Reason: image not found

```
<img width="1019" alt="screen shot 2018-11-18 at 19 36 47" src="https://user-images.githubusercontent.com/6923008/48679663-6b5ab400-eb69-11e8-898c-bf26e20bcd80.png">

**Comment by jdent02** [comment]
Yes, I held on to 21.7.  Pixar hasn't approved any significant changes to this exporter since last year so I was pretty positive it wouldn't work with 22.

**Comment by pleprince** [comment]
One of our engineers started working on the new plugin but we don't have a release date yet. It is all hinging on the public availability of our new API...

**Comment by schroef** [comment]
Why not keep old api available by the way? I dont understand this is only available once you pay the license.

**Comment by schroef** [comment]
You don't need to support old API, if you state that only latest new releases are supported. Thats how many other applications also handle it.
