### ISSUE TITLE
renderman addon errors while loading

### ISSUE THREAD

**Issue by vikipretium** [prman-pixar/RenderManForBlender#581]
![image](https://user-images.githubusercontent.com/20333314/45472489-fffffa80-b751-11e8-87fa-212dadfad1d5.png)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\Aeroboy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\__init__.py", line 119, in register
    load_addon()
  File "C:\Users\Aeroboy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\__init__.py", line 94, in load_addon
    if guess_rmantree():
  File "C:\Users\Aeroboy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\util.py", line 553, in guess_rmantree
    "Error loading addon.  RMANTREE %s is not valid.  Correct RMANTREE setting in addon preferences." % rmantree)
  File "C:\Users\Aeroboy\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RenderManForBlender-master\util.py", line 59, in throw_error
    raise ImportError(msg)
ImportError: Error loading addon.  RMANTREE  is not valid.  Correct RMANTREE setting in addon preferences.

**Comment by sollozzo13** [comment]
Is there anybody in there?

**Comment by vikipretium** [comment]
> Is there anybody in there?

yup
