### ISSUE TITLE
Crash when enabled RenderMan on 2.79

### ISSUE THREAD

**Issue by linuxjet** [prman-pixar/RenderManForBlender#583]
I am running OSX 10.13.6 and Blender 2.79.6 and The4 BlenderMan pluging installs but crashes when attempting to enable.  

![screen shot 2018-09-28 at 8 34 30 am](https://user-images.githubusercontent.com/378474/46211618-a246e300-c2f9-11e8-8125-779bf72e5468.png)

**Comment by jdent02** [comment]
If I recall correctly the extensions framework has been removed from Blender for quite a while (since shortly after 2.79b).  If you want this plugin to work, stick with 2.79b official.  Daily builds have also been on Python 3.7 for a while and Renderman 21 only went up to 3.5 I believe.

**Comment by linuxjet** [comment]
I reverted back to 79b and still getting an error.   Different, but still error.
<img width="843" alt="screen shot 2018-09-28 at 1 45 35 pm" src="https://user-images.githubusercontent.com/378474/46227474-eef3e380-c324-11e8-9763-5d08900fb893.png">

**Comment by jdent02** [comment]
Is there a -master on the folder name?  If so remove it

**Comment by linuxjet** [comment]
there is no -master . - I was using the 21-4 branch for that I guess.  I just tried the 21-5 release and master branch and still getting error
<img width="797" alt="screen shot 2018-09-28 at 3 00 04 pm" src="https://user-images.githubusercontent.com/378474/46230805-60389400-c32f-11e8-9314-6cfefe29cfff.png">

**Comment by waebbl** [comment]
I'm also having trouble enabling 21.5 with blender-2.79b. I'm using renderman 22 NCR on a gentoo linux box with python 3.6.5

```
Exception in module register(): '/usr/share/blender/2.79/scripts/addons/renderman-for-blender/__init__.py'
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 350, in enable
    mod.register()
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/__init__.py", line 119, in register
    load_addon()
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/__init__.py", line 104, in load_addon
    properties.register()
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/properties.py", line 2570, in register
    register_plugin_types()
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/properties.py", line 2524, in register_plugin_types
    register_plugin_to_parent(ntype, name, args_xml, plugin_type, parent)
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/properties.py", line 2485, in register_plugin_to_parent
    class_generate_properties(ntype, name, inputs)
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/shader_parameters.py", line 175, in class_generate_properties
    sp, node, page_name, first_level=first_level)
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/shader_parameters.py", line 85, in generate_page
    name, meta, prop = generate_property(sub_param)
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/shader_parameters.py", line 448, in generate_property
    sp.find("hintdict[@name='conditionalVisOps']"))
  File "/usr/share/blender/2.79/scripts/addons/renderman-for-blender/shader_parameters.py", line 343, in parse_conditional_visop
    "string[@name='conditionalVis2Path']").attrib['value']
AttributeError: 'NoneType' object has no attribute 'attrib'
```
