### ISSUE TITLE
[q] Getting error 'Image not found'

### ISSUE THREAD

**Issue by schroef** [prman-pixar/RenderManForBlender#586]
v 22.2
bl 2.78c and 2.79b
osx 10.11.6

I just tried using this addin and in both bl 2.78c and 2.79b i get this error 'Image not found'

Below you can see the complete output of the console. I think this is related to the python  lib used by both bl 2.78c and 2.79b, both use 3.5 i believe

How can use this addon in the correct way than? 

```
Exception ignored in: <bound method RPass.__del__ of <RenderManForBlender.engine.RPass object at 0x1197c8fd0>>
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 220, in __del__
    del self.ri
AttributeError: ri
Exception ignored in: <bound method PRManRender.__del__ of <bpy_struct, PRManRender invalid>>
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/__init__.py", line 51, in __del__
    if hasattr(self, "render_pass"):
ReferenceError: StructRNA of type PRManRender has been removed
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/operators.py", line 492, in invoke
    engine.ipr = RPass(context.scene, interactive=True)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 204, in __init__
    init_prman()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 79, in init_prman
    import prman
  File "/Applications/Pixar/RenderManProServer-22.2/bin/prman.py", line 80, in <module>
    import prman_for_python_35 as prman_for_python
ImportError: dlopen(/Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python
  Referenced from: /Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so
  Reason: image not found

location: <unknown location>:-1
```

**Comment by schroef** [comment]
Okay after some more googling i just found that this addon is useless now. We cant use RM 22 and there is no way to get it unless you pay for the app. Thats really a shame, i would love to try this engine.
