### ISSUE TITLE
Error while starting IPR or Rendering.

### ISSUE THREAD

**Issue by MinshuG** [prman-pixar/RenderManForBlender#597]
This happens whenever I try to render or switch to IPR.

Traceback :-
```python-traceback
Python: Traceback (most recent call last):
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\__init__.py", line 86, in view_update
    self.rman_render.start_interactive_render(context, depsgraph)
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_render.py", line 782, in start_interactive_render
    self.rman_scene.export_for_interactive_render(context, depsgraph, self.sg_scene)
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 243, in export_for_interactive_render
    self.export()
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 328, in export
    self.export_instances()
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 810, in export_instances
    self._export_instance(ob_inst)
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 735, in _export_instance
    translator.update(ob, rman_sg_node)
  File "C:\Users\Minshu\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_translators\rman_mesh_translator.py", line 365, in update
    scenegraph_utils.set_material(sg_node, sg_material.sg_node)
NameError: name 'sg_node' is not defined
```

**Comment by prman-pixar** [comment]
I posted a fix for this on discord. I will push the fix to github in a bit, but if you want to fix it yourself, 

In RenderManForBlender/rman_translators/rman_mesh_translator.py, change line 365 to:
scenegraph_utils.set_material(rman_sg_mesh.sg_node, sg_material.sg_node)

**Comment by mattjdnv** [comment]
Thank you very much! I now have Blender and RenderMan working.
