### ISSUE TITLE
Python error after importing an object

### ISSUE THREAD

**Issue by henrikmk** [prman-pixar/RenderManForBlender#600]
Or loading any existing blender file, really.

The following python error appears in the system console window, when attempting to activate IPR:

```
Python: Traceback (most recent call last):
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\__init__.py", line 86, in view_update
    self.rman_render.start_interactive_render(context, depsgraph)
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_render.py", line 782, in start_interactive_render
    self.rman_scene.export_for_interactive_render(context, depsgraph, self.sg_scene)
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 243, in export_for_interactive_render
    self.export()
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 328, in export
    self.export_instances()
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 810, in export_instances
    self._export_instance(ob_inst)
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 735, in _export_instance
    translator.update(ob, rman_sg_node)
  File "C:\Users\henrikmk\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_translators\rman_mesh_translator.py", line 365, in update
    scenegraph_utils.set_material(sg_node, sg_material.sg_node)
NameError: name 'sg_node' is not defined

location: <unknown location>:-1
```

After that, IPR is dead and Blender must be restarted. Happens both in 2.83 LTS and 2.92.

**Comment by nathanhitch** [comment]
from what ive figured out is that it doesnt like objects with multiple materials

**Comment by prman-pixar** [comment]
That should be fixed now with the latest commits. Thanks for the report!
