### ISSUE TITLE
RenderMan Blender add-ons not installing

### ISSUE THREAD

**Issue by Vkuzmeniuk** [prman-pixar/RenderManForBlender#606]
![image](https://user-images.githubusercontent.com/77533405/125510659-5e1f0a5e-e72f-4ea2-8af9-69771869f371.png)
![image](https://user-images.githubusercontent.com/77533405/125510686-68a11702-aca1-425e-b8ee-822983e23ea4.png)

Traceback (most recent call last):
  File "C:\Program Files\Pixar\RenderManProServer-24.0\bin\rman_utils\rman_assets\common\shading_node.py", line 14, in <module>
    import oslquery as oslq
ModuleNotFoundError: No module named 'oslquery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\vladi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RenderManForBlender\__init__.py", line 244, in register
    load_addon()
  File "C:\Users\vladi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RenderManForBlender\__init__.py", line 213, in load_addon
    from . import rman_presets
  File "C:\Users\vladi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RenderManForBlender\rman_presets\__init__.py", line 27, in <module>
    from . import ui
  File "C:\Users\vladi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RenderManForBlender\rman_presets\ui.py", line 40, in <module>
    from . import rmanAssetsBlender as rab
  File "C:\Users\vladi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RenderManForBlender\rman_presets\rmanAssetsBlender.py", line 26, in <module>
    from rman_utils.rman_assets import core as ra
  File "C:\Program Files\Pixar\RenderManProServer-24.0\bin\rman_utils\rman_assets\core.py", line 57, in <module>
    from rman_utils.rman_assets.common.shading_node import RmanShadingNode # pylint: disable=unused-import
  File "C:\Program Files\Pixar\RenderManProServer-24.0\bin\rman_utils\rman_assets\common\shading_node.py", line 16, in <module>
    import oslquery as oslq
ModuleNotFoundError: No module named 'oslquery'

**Comment by prman-pixar** [comment]
2.93 is current not supported. It will be supported when RenderMan 24.1 ships.
