### ISSUE TITLE
Render Holdouts Not Working

### ISSUE THREAD

**Issue by awils27** [prman-pixar/RenderManForBlender#609]
Blender 2.92
Windows 10 20H2
Renderman Plugin v24.0.1

Enable either of the holdout options in renderman will prevent anything from rendering. IPR stops at "Exporting Data Blocks 95%". Or if no Holdouts in scene just closes Blender. Final renders just do nothing, rendering to Blender or IT makes no difference.

**Comment by prman-pixar** [comment]
@awils27 can you give me a blend file?

**Comment by awils27** [comment]
Default scene with Render holdouts set to In Alpha or Separate AOV is all it takes. Got an Error code this time. Optix denoising is turned off so not sure why it is mentioning it. Using an RTX 3090 incase that is relevant, I do not have the commercial version of renderman. 

>Python: Traceback (most recent call last):
  File "C:\Users\aid28\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\__init__.py", line 157, in render
    if not self.rman_render.start_render(depsgraph, for_background=for_background):
  File "C:\Users\aid28\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_render.py", line 466, in start_render
    self.rman_scene.export_for_final_render(depsgraph, self.sg_scene, bl_layer, is_external=is_external)
  File "C:\Users\aid28\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 214, in export_for_final_render
    self.export()
  File "C:\Users\aid28\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 322, in export
    self.export_hider()
  File "C:\Users\aid28\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rman_scene.py", line 1097, in export_hider
    dspys_dict = display_utils.get_dspy_dict(self)
  File "C:\Users\aid28\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RenderManForBlender\rfb_utils\display_utils.py", line 640, in get_dspy_dict
    _set_rman_holdouts_dspy_dict(dspys_dict, display_driver, rman_scene, expandTokens, do_optix_denoise=do_optix_denoise)  
TypeError: _set_rman_holdouts_dspy_dict() got an unexpected keyword argument 'do_optix_denoise'
location: <unknown location>:-1

[HoldoutError.zip](https://github.com/prman-pixar/RenderManForBlender/files/6869864/HoldoutError.zip)

**Comment by prman-pixar** [comment]
@awils27  that should have been fixed in at least the hotfix release. Can you try that version and see if it works for you?

https://github.com/prman-pixar/RenderManForBlender/releases/tag/v24.0.1
