### ISSUE TITLE
Add support for Microsoft store installation path

### ISSUE THREAD

**Issue by Aiacos** [prman-pixar/RenderManForBlender#647]
this is the issue loading rman plugin:
Exception in module register(): C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.0.1.0_x64__ppwjx1n5r4v9t\Blender\3.0\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\__init__.py", line 310, in register
    load_addon()
  File "C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\__init__.py", line 276, in load_addon
    from . import rman_presets
  File "C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\rman_presets\__init__.py", line 27, in <module>
    from . import ui
  File "C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\rman_presets\ui.py", line 40, in <module>
    from . import rmanAssetsBlender as rab
  File "C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\rman_presets\rmanAssetsBlender.py", line 45, in <module>
    from ..rfb_utils import transform_utils
  File "C:\Users\unilo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RenderManForBlender\rfb_utils\transform_utils.py", line 1, in <module>
    import rman
  File "C:\Program Files\Pixar\RenderManProServer-24.3\bin\pythonbindings\rman\__init__.py", line 5, in <module>
    import rman.__39__.RiCtl as RiCtl
  File "C:\Program Files\Pixar\RenderManProServer-24.3\bin\pythonbindings\rman\__39__\RiCtl.py", line 24, in <module>
    from ._RiCtl import *
ImportError: DLL load failed while importing _RiCtl

**Comment by prman-pixar** [comment]
@Aiacos This is a known issue when using Blender downloaded from the Microsoft store. We have not been able to pinpoint the problem. However, builds from blender.org work.

**Comment by prman-pixar** [comment]
@Aiacos  can you see if the latest commit in the dev branch fixes the problem you're seeing with the Windows/Microsoft store version of Blender?
