### ISSUE TITLE
Error when installing an addon for Blender 3.1 and higher.

### ISSUE THREAD

**Issue by Igrom4ik** [prman-pixar/RenderManForBlender#657]
This error occurs in blender version 3.1 and higher. Will there be support for the latest versions of blender or is this expected with Renderman 2.5?

Traceback (most recent call last):
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\common\shading_node.py", line 14, in <module>
    import oslquery as oslq
  File "C:\Program Files\Pixar\RenderManProServer-24.4\lib\python3.9\Lib\site-packages\oslquery\__init__.py", line 42, in <module>
    from oslquery._oslquery import *
ImportError: Module use of python39.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Igrom\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender\__init__.py", line 313, in register
    load_addon()
  File "C:\Users\Igrom\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender\__init__.py", line 277, in load_addon
    from . import rman_presets
  File "C:\Users\Igrom\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender\rman_presets\__init__.py", line 27, in <module>
    from . import ui
  File "C:\Users\Igrom\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender\rman_presets\ui.py", line 40, in <module>
    from . import rmanAssetsBlender as rab
  File "C:\Users\Igrom\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender\rman_presets\rmanAssetsBlender.py", line 25, in <module>
    from rman_utils.rman_assets import lib as ral
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\lib.py", line 50, in <module>
    import rman_utils.rman_assets.core as ra
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\core.py", line 59, in <module>
    from rman_utils.rman_assets.common.shading_node import RmanShadingNode  # pylint: disable=unused-import
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\common\shading_node.py", line 16, in <module>
    import oslquery as oslq
  File "C:\Program Files\Pixar\RenderManProServer-24.4\lib\python3.9\Lib\site-packages\oslquery\__init__.py", line 42, in <module>
    from oslquery._oslquery import *
ImportError: Module use of python39.dll conflicts with this version of Python.

**Comment by prman-pixar** [comment]
@Igrom4ik Blender 3.1, 3.2 support should be coming during the RenderMan 25 timeframe.
