### ISSUE TITLE
Can't install on Blender version 3.1.1

### ISSUE THREAD

**Issue by noc2art** [prman-pixar/RenderManForBlender#661]
The addon can't be activated on 3.1.1 Churns out the following errors:

Modules Installed (RenderManForBlender-main) from 'C:\\Users\\ajlan\\Downloads\\RenderManForBlender-main.zip' into 'C:\\Users\\ajlan\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
[DEBUG] (MainThread) RenderManForBlender-main.rfb_logger init_log_level: logger initialized
[DEBUG] (MainThread) RenderManForBlender-main.rfb_logger init_log_level:    |_ logger: 0
Exception in module register(): C:\Users\ajlan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender-main\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\common\shading_node.py", line 14, in <module>
    import oslquery as oslq
  File "C:\Program Files\Pixar\RenderManProServer-24.4\lib\python3.9\Lib\site-packages\oslquery\__init__.py", line 42, in <module>
    from oslquery._oslquery import *
ImportError: DLL load failed while importing _oslquery: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\ajlan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender-main\__init__.py", line 313, in register
    load_addon()
  File "C:\Users\ajlan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender-main\__init__.py", line 277, in load_addon
    from . import rman_presets
  File "C:\Users\ajlan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender-main\rman_presets\__init__.py", line 27, in <module>
    from . import ui
  File "C:\Users\ajlan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender-main\rman_presets\ui.py", line 40, in <module>
    from . import rmanAssetsBlender as rab
  File "C:\Users\ajlan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RenderManForBlender-main\rman_presets\rmanAssetsBlender.py", line 25, in <module>
    from rman_utils.rman_assets import lib as ral
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\lib.py", line 50, in <module>
    import rman_utils.rman_assets.core as ra
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\core.py", line 59, in <module>
    from rman_utils.rman_assets.common.shading_node import RmanShadingNode  # pylint: disable=unused-import
  File "C:\Program Files\Pixar\RenderManProServer-24.4\bin\rman_utils\rman_assets\common\shading_node.py", line 16, in <module>
    import oslquery as oslq
  File "C:\Program Files\Pixar\RenderManProServer-24.4\lib\python3.9\Lib\site-packages\oslquery\__init__.py", line 42, in <module>
    from oslquery._oslquery import *
ImportError: DLL load failed while importing _oslquery: The specified module could not be found.****

**Comment by prman-pixar** [comment]
We currently do not support Blender 3.3.x. The latest version we can support currently is 3.0.x.
