### ISSUE TITLE
unable to enable add on on M1 Mac

### ISSUE THREAD

**Issue by pallazola** [prman-pixar/RenderManForBlender#675]
This is the error I get when trying to enable the addon on Blender 3.0 (Apple silicon):
```
Traceback (most recent call last):
  File "/Applications/Blender 3.0/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/__init__.py", line 86, in register
    load_addon()
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/__init__.py", line 55, in load_addon
    from . import rman_presets
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/rman_presets/__init__.py", line 29, in <module>
    from . import ui
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/rman_presets/ui.py", line 29, in <module>
    from ..rman_ui import rfb_qt
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/rman_ui/__init__.py", line 2, in <module>
    from . import rman_ui_txmanager
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/rman_ui/rman_ui_txmanager.py", line 6, in <module>
    from ..rfb_utils import texture_utils
  File "/Users/mike/Library/Application Support/Blender/3.0/scripts/addons/RenderManForBlender/rfb_utils/texture_utils.py", line 10, in <module>
    from rman_utils.txmanager import core as txcore
  File "/Applications/Pixar/RenderManProServer-25.0/bin/rman_utils/txmanager/core.py", line 73, in <module>
    from rman_utils.txmanager.txfile import TxFile, _reset_rule_filecache
  File "/Applications/Pixar/RenderManProServer-25.0/bin/rman_utils/txmanager/txfile.py", line 22, in <module>
    import ice  # pylint: disable=import-error
  File "/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/__init__.py", line 35, in <module>
    from ice._ice import *
ImportError: dlopen(/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so, 0x0002): tried: '/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so' (no such file), '/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))


```

On Blender 2.93 I can enable the addon but none of the options show-up inside Blender, I can't choose RenderMan as a render engine or see any RenderMan stuff anywhere. This is the error when running Blender from the command line:

```
Exception in module register(): /Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender 2.93/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/__init__.py", line 86, in register
    load_addon()
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/__init__.py", line 55, in load_addon
    from . import rman_presets
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/rman_presets/__init__.py", line 29, in <module>
    from . import ui
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/rman_presets/ui.py", line 29, in <module>
    from ..rman_ui import rfb_qt
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/rman_ui/__init__.py", line 2, in <module>
    from . import rman_ui_txmanager
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/rman_ui/rman_ui_txmanager.py", line 6, in <module>
    from ..rfb_utils import texture_utils
  File "/Users/mike/Library/Application Support/Blender/2.93/scripts/addons/RenderManForBlender/rfb_utils/texture_utils.py", line 10, in <module>
    from rman_utils.txmanager import core as txcore
  File "/Applications/Pixar/RenderManProServer-25.0/bin/rman_utils/txmanager/core.py", line 73, in <module>
    from rman_utils.txmanager.txfile import TxFile, _reset_rule_filecache
  File "/Applications/Pixar/RenderManProServer-25.0/bin/rman_utils/txmanager/txfile.py", line 22, in <module>
    import ice  # pylint: disable=import-error
  File "/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/__init__.py", line 35, in <module>
    from ice._ice import *
ImportError: dlopen(/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so, 0x0002): tried: '/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so' (no such file), '/Applications/Pixar/RenderManProServer-25.0/lib/python3.9/site-packages/ice/_ice.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

I'm on a MacStudio with Apple M1 Ultra running Ventura 13.3.1 (a)

**Comment by pallazola** [comment]
OK that will do it!
> @pallazola You cannot use the M1 version of Blender with RenderMan. You have to use the Intel version.
