### ISSUE TITLE
RenderMan 25 crashes in Blender 2.83LTS

### ISSUE THREAD

**Issue by hareurs** [prman-pixar/RenderManForBlender#676]
After installing RenderMan plugin for Blender 2.83LTS and click the tick of the plugin to enable it, the system blender throws the following error message:

<details>
<summary>DLL Load Failed</summary>

```
Traceback (most recent call last):
  File "D:\Blender\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\__init__.py", line 86, in register
    load_addon()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\__init__.py", line 55, in load_addon
    from . import rman_presets
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\rman_presets\__init__.py", line 29, in <module>
    from . import ui
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\rman_presets\ui.py", line 29, in <module>
    from ..rman_ui import rfb_qt
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\rman_ui\__init__.py", line 2, in <module>
    from . import rman_ui_txmanager
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\rman_ui\rman_ui_txmanager.py", line 14, in <module>
    from .. import rman_render
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RenderManForBlender\rman_render.py", line 3, in <module>
    import rman
  File "C:\Program Files\Pixar\RenderManProServer-25.0\bin\pythonbindings\rman\__init__.py", line 16, in <module>
    import rman.__37__.RiCtl as RiCtl
  File "C:\Program Files\Pixar\RenderManProServer-25.0\bin\pythonbindings\rman\__37__\RiCtl.py", line 24, in <module>
    from ._RiCtl import *
ImportError: DLL load failed: The specified module could not be found.
```
</details>

**System Information**:
- OS: Windows 10 Pro 21H2, Build 19044.2965
- CPU: 12th Intel Core i5-12400
- GPU: Intel UHD Graphics 730; NVIDIA GeForce RTX 3600

**How to Reproduce**:
1. Download and install Blender 2.83LTS
2. Use RenderMan installer to install RenderMan 25 and the corresponding blender plugin
3. Add the .zip file of RenderMan plugin to the Blender add-on, and enable it. You would see an error message popping up.

**Comment by prman-pixar** [comment]
Just as a test, can you try upgrading to 2.93LTS and see if that works?

**Comment by prman-pixar** [comment]
Note, for the just released RenderMan 25.1, we've dropped support for Blender 2.83LTS.

**Comment by hareurs** [comment]
It works in 2.93LTS.

**Comment by hareurs** [comment]
I will switch to 2.93LTS then. Closing this issue now.
