### ISSUE TITLE
"IndexError: tuple index out of range" when disconnecting nodes

### ISSUE THREAD

**Issue by erjiang** [prman-pixar/RenderManForBlender#694]
Doesn't seem to stop anything obvious from working, but prints this exception to the log:
```
Traceback (most recent call last):
  File "/home/eric/.config/blender/3.6/scripts/addons/RenderManForBlender/rman_bl_nodes/rman_bl_nodes_shaders.py", line 90, in draw_buttons
    self.draw_nonconnectable_props(context, layout, self.prop_names, output_node=out_node)
  File "/home/eric/.config/blender/3.6/scripts/addons/RenderManForBlender/rman_bl_nodes/rman_bl_nodes_shaders.py", line 373, in draw_nonconnectable_props
    self.draw_nonconnectable_prop(context, layout, prop_name, output_node=output_node, level=level)
  File "/home/eric/.config/blender/3.6/scripts/addons/RenderManForBlender/rman_bl_nodes/rman_bl_nodes_shaders.py", line 146, in draw_nonconnectable_prop
    bl_prop_info = BlPropInfo(node, prop_name, prop_meta)
  File "/home/eric/.config/blender/3.6/scripts/addons/RenderManForBlender/rfb_utils/property_utils.py", line 90, in __init__
    self.link = self.socket.links[0]
IndexError: tuple index out of range

```

Steps to reproduce:

1. Connect PxrArithmetic.resultRGB to PxrConstant.emitColor.
2. Disconnect that connection.
3. See exception in logs.

**Comment by prman-pixar** [comment]
Should be fixed now with the latest commit.
