### ISSUE TITLE
Mac M2 via Rosetta possible?

### ISSUE THREAD

**Issue by enzyme69** [prman-pixar/RenderManForBlender#704]
I installed the addon on Mac M2 and it does not work. Is this the case even today? Can I run it via Rosetta?

The addon I downloaded from this Github does not give error message, but the one comes with installation give the error:

```
Traceback (most recent call last):
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/__init__.py", line 86, in register
    load_addon()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/__init__.py", line 55, in load_addon
    from . import rman_presets
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/rman_presets/__init__.py", line 29, in <module>
    from . import ui
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/rman_presets/ui.py", line 29, in <module>
    from ..rman_ui import rfb_qt
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/rman_ui/__init__.py", line 2, in <module>
    from . import rman_ui_txmanager
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/rman_ui/rman_ui_txmanager.py", line 6, in <module>
    from ..rfb_utils import texture_utils
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/RenderManForBlender/rfb_utils/texture_utils.py", line 10, in <module>
    from rman_utils.txmanager import core as txcore
  File "/Applications/Pixar/RenderManProServer-25.2/bin/rman_utils/txmanager/core.py", line 73, in <module>
    from rman_utils.txmanager.txfile import TxFile, _reset_rule_filecache
  File "/Applications/Pixar/RenderManProServer-25.2/bin/rman_utils/txmanager/txfile.py", line 22, in <module>
    import ice  # pylint: disable=import-error
  File "/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/ice/__init__.py", line 35, in <module>
    from ice._ice import *
ImportError: dlopen(/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/ice/_ice.so, 0x0002): tried: '/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/ice/_ice.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/ice/_ice.so' (no such file), '/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/ice/_ice.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```

**Comment by enzyme69** [comment]
UPDATE: 
You can use the Renderman addon using Blender Intel version (it will run via Rosetta in macOS automatically)! Thanks to Pixar guy Dylan.
