### ISSUE TITLE
Can't install Renderman addon in Blender - Ubuntu 20.04

### ISSUE THREAD

**Issue by lukas-remis** [prman-pixar/RenderManForBlender#708]
Hi,

I've installed Renderman using the installer, but I'm unable to install the addon.
Getting those errors:

Traceback (most recent call last):
  File "/media/lukas/VFX/.Pipeline/Blender/blender-latest/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/__init__.py", line 87, in register
    load_addon()
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/__init__.py", line 56, in load_addon
    from . import rman_presets
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/rman_presets/__init__.py", line 29, in <module>
    from . import ui
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/rman_presets/ui.py", line 45, in <module>
    from . import rmanAssetsBlender as rab
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/rman_presets/rmanAssetsBlender.py", line 38, in <module>
    from . import core as bl_pb_core
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/rman_presets/core.py", line 20, in <module>
    from ..rman_bl_nodes import __BL_NODES_MAP__, __RMAN_NODE_TYPES__
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/rman_bl_nodes/__init__.py", line 34, in <module>
    from . import rman_bl_nodes_sockets
  File "/opt/cgru/plugins/blender/addons/RenderManForBlender/rman_bl_nodes/rman_bl_nodes_sockets.py", line 28, in <module>
    from bpy.types import (NodeSocketFloat,
ImportError: cannot import name 'NodeSocketInterfaceFloat' from 'bpy.types' (unknown location)

Lukas

**Comment by lukas-remis** [comment]
My bad, wrong Blender version.
