### ISSUE TITLE
Error message : Export failed 'None Type ' object has no attribute 'name_full'

### ISSUE THREAD

**Issue by marcrupprath** [prman-pixar/RenderManForBlender#715]
Hello,
 i am new using Rendermann on Blender. i have Blender 4.3 and RenderManForBlender Versiojn 26.2_2336968

I tried a quick and dirty test by rendering classrom demo cene with blenderman an it failed.

Did not know meaning of erro message 

Question is how to render originaly scene made fpr cycles and eve with rendermann ?

Thanks in advance

**Comment by marcrupprath** [comment]
I have tried but error is the same:
As mentioned in pther posts i have found.
It seams that there is now easy way to convert Cycles to blendermann , youn have to recreate materaisl from scrath

Corrwect me when i am wron ynd you have a more somplier solution for this

**Comment by prman-pixar** [comment]
Yes, it's recommended that you create the materials from scratch. There is code that attempts to do a conversion, but it does not work in all cases, so it is hidden.

**Comment by marcrupprath** [comment]
Would you kindly remov the option in the preference settings until this function has proved its realiablity ?
It is very confusinf /disapointing having options selectable that causes more trouble than usefull results if selected.

I have tested some other scenes and even you get no error message sometimes only 1/4 of scene are rendered

**Comment by prman-pixar** [comment]
I'd like to keep the option around for testing purposes. We already explain that this doesn't work in all cases in the tool tip, but I can make it more explicit.

**Comment by nicmr** [comment]
Hi @prman-pixar, we are encountering the same issue and I hope a backtrace might help in fixing this problem:

```
[ERROR] (MainThread) RenderManForBlender.rfb_logger start_interactive_render: Export Failed:
Traceback (most recent call last):
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rman_render.py", line 1188, in start_interactive_render
    self.rman_scene.export_for_interactive_render(context, depsgraph, self.sg_scene)
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rman_scene.py", line 259, in export_for_interactive_render
    self.export()
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rman_scene.py", line 323, in export
    self.export_data_blocks()
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rman_scene.py", line 731, in export_data_blocks
    rman_sg_node = self.get_rman_prototype(proto_key, ob=ob_eval, create=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rman_scene.py", line 1008, in get_rman_prototype
    rman_sg_node = self.export_data_block(proto_key, ob)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rman_scene.py", line 846, in export_data_block
    parent_proto_key = object_utils.prototype_key(ob.original.parent)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foo\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RenderManForBlender\rfb_utils\object_utils.py", line 230, in prototype_key
    return '%s-MESH-DATA' % data_ob.original.data.name_full
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name_full
```

It occurs regardless of the `Convert Cycles Nodes` option in the addon preferences being selected or not.
Please let me know if you would like me to open a separate issue.

Version Information:
Blender: 4.3.2
RenderMan: 26.3
RenderManForBlender: 26.3 (2352291) (although this build is reported as 26.2 in the Blender UI)
